name: CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install packages
        run: make install
      - name: lint
        run: make lint
      # - name: test
      #   run: make test
      - name: format
        run: make format
      - name: run program and generate PDF file
        run: make run
      - name: push PDF file to GitHub
        run: make push
